TEMPLATE_DIR = ~/Library/Developer/Xcode/Templates/
SILVER_PLATTER = silver-platter
SILVER_PLATTER_DIRECTORY = $(TEMPLATE_DIR)$(SILVER_PLATTER)
FILE_TEMPLATES = 'File Templates'
PROJECT_TEMPLATES = 'Project Templates'

all:
	rm -rf $(SILVER_PLATTER_DIRECTORY)
	mkdir $(SILVER_PLATTER_DIRECTORY)
	cp -r $(FILE_TEMPLATES) $(SILVER_PLATTER_DIRECTORY)
	cp -r $(PROJECT_TEMPLATES) $(SILVER_PLATTER_DIRECTORY)
