//
//  TextQuestionWorkerTests.swift
//  Chesterfield
//
//  Created by Håkon Bogen on 22/06/2018,25.
//  Copyright (c) 2018 Beining & Bogen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Chesterfield
import XCTest

class TextQuestionWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: TextQuestionWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupTextQuestionWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupTextQuestionWorker()
  {
    sut = TextQuestionWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testSomething()
  {
    // Given
    
    // When
    
    // Then
  }
}
