//
//  TextQuestionInteractorTests.swift
//  Chesterfield
//
//  Created by Håkon Bogen on 22/06/2018,25.
//  Copyright (c) 2018 Beining & Bogen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Chesterfield
import XCTest

class TextQuestionInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: TextQuestionInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupTextQuestionInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupTextQuestionInteractor()
  {
    sut = TextQuestionInteractor()
  }
  
  // MARK: Test doubles
  
  class TextQuestionPresentationLogicSpy: TextQuestionPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: TextQuestion.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = TextQuestionPresentationLogicSpy()
    sut.presenter = spy
    let request = TextQuestion.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
