//
//  TextQuestionPresenterTests.swift
//  Chesterfield
//
//  Created by Håkon Bogen on 22/06/2018,25.
//  Copyright (c) 2018 Beining & Bogen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Chesterfield
import XCTest

class TextQuestionPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: TextQuestionPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupTextQuestionPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupTextQuestionPresenter()
  {
    sut = TextQuestionPresenter()
  }
  
  // MARK: Test doubles
  
  class TextQuestionDisplayLogicSpy: TextQuestionDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: TextQuestion.Something.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = TextQuestionDisplayLogicSpy()
    sut.viewController = spy
    let response = TextQuestion.Something.Response()
    
    // When
    sut.presentSomething(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
